[tool.poetry]
name = "bayesian-deep-learning"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "*"
black = {version = "*", allow-prereleases = true}
isort = "*"
flake8 = "*"
taskipy = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
test = "poetry run pytest"
lint = "poetry run black . && poetry run isort . && poetry run flake8 tests"

[tool.black]
line-length = 88
include = "\\.pyi?$"
exclude = """
/(
    \\.git
  | \\.tox
  | \\.venv
  | notebooks
  | reports
)/
"""
