[tool.poetry]
name = "bayesian-deep-learning"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "*"
tensorflow = "2.*"

[tool.poetry.dev-dependencies]
jupyter = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
